name: Update DuckCare Report

on:
  workflow_dispatch:

jobs:

  report:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      - run: pip install pandas numpy requests

      - run: python scripts/generate_report.py

      - name: Commit JSON

        run: |

          git config user.name "BeningCahyaA"

          git config user.email "beningcahya873@gmail.com"

          git add output/report_harga_telur.json

          git commit -m "Update Report" || echo "No changes"

          git push
